Fix android build error specifying audiodev extensions requirements.
This commit introduce the variable HAVE_SYS_SOUNDCARD_H and fix the
following build error:

//-------------
Building C object CMakeBuild/extensions/CMakeFiles/extension_ossaudiodev.dir/data/data/com.termux/files/home/Python-2.7.10/Modules/ossaudiodev.c.o
/data/data/com.termux/files/home/Python-2.7.10/Modules/ossaudiodev.c:33:27: fatal error: sys/soundcard.h: No such file or directory
 #include <sys/soundcard.h>
//-------------